### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by RodolfoRodriguezMata**

### CODE REVIEW

**Comment by ebukaume** [comment]
## Changes Required! :stop_sign: 

Hi @RodolfoRodriguezMata  and @mohamedSabry0  :wave: 

You guys are doing well so far. Let's address these issues so we can move forward. 

review-intuit-logo

- [ ] The intuit logo, product logo and texts should each be a different element.
- [ ] Your clone doesn't quite feel like the original page.

_**Their**_
review-intuit-main

_**Yours**_
review-intuit-clone

_**Pay close attention to the gaps between the elements inside the form; the size and feel of the disclaimer text :wink:  I believe you guys can do much better.**_

- [ ] Using `!important` this way is considered a bad practice. See [this article](https://speckyboy.com/good-bad-css-practices). 
https://github.com/mohamedSabry0/signup-form/blob/83cd5fea6de98dd9fed5c922f12e76bf37b8082c/style.css#L28-L38

- [ ] Your HTML document contains validation errors. Use [this service](https://validator.w3.org/nu/#textarea) to always check your HTML docs. _Please fix this errors._

**Kindly submit another code review request after fixing these issues.**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Comment by shshamim63** [comment]
### Changes Required!
___
Hi @RodolfoRodriguezMata  and @mohamedSabry0 ,
Nice work :clap: so far, almost near to complete the project. But you have to cover some issues that has already been mentioned by @ebukaume  to declare this project as complete. 
#### Please follow the instructions below :point_down: 
### [Mandatory Changes]!
___
1. Your form does not contain a intuit logo. and some other logo with their respective name. Now the question [Why are we again and again telling you to do so?] Ans: Well, this logo and icon section is a tricky part, consists tiny particles that you need to handle. It will provide you a good concept about the sizing and positioning. 
On you project this critical part has been replaced by an image. But if you check the actual webpage you will see that it consists of differenet logo and their name.
intuit
2. The more you will try to copy the actual webpage you will understand the flow of the structure. So I believe you will give another shot on your form part to make it as close as possible as the original webpage.
##### Actual one -> 
actualbody
##### Your one ->
yourone
___
#### Please Fix the above mentioned issue and ask for another review request to achieve your final destination of this project.

___
### Happy Coding!
##### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawat-hossain-7750b0127/) | [Slack](Shakhawat hossain).

**Comment by RodolfoRodriguezMata** [comment]
@shshamim63 Hello Shakhawat I believe we have already addressed those points this time, could you please give it another look? 
Here's a live version:
https://raw.githack.com/mohamedSabry0/signup-form/feature-branch/index.html
we made sure to split the logos, change the spacing, remove the !important rules and the validation

**Comment by shshamim63** [comment]
### Status Approved! :tada: 
___
Hi @RodolfoRodriguezMata  and @mohamedSabry0 , 
You guys have nailed it. I can see all the components are almost on the same part. But a simple one i will mention is the form footer 
form
font size 10px is the right one i believe.
___
### This :+1:  is from me, you can merge it and don't forget to fill the project completion form.
 
___
### Happy Coding!
##### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawat-hossain-7750b0127/) | [Slack](Shakhawat hossain).

**Comment by RodolfoRodriguezMata** [comment]
Thank you for your quick reply and for pointing that out, we believe it's fixed now and will proceed to merge.
Thanks again and happy coding!

**Pull request merged**
